regions:
- sa-east-1 # Sao Paulo
- us-east-1 # North Virginia
- eu-central-2 # Zürich
- eu-central-1 # Frankfurt
- eu-north-1 # Stockholm
- eu-west-1 # Ireland
- global

account-blocklist:
- "999999999999" # production

resource-types:
  excludes:
  - Route53HostedZone

accounts:
  "298410952490":
    filters:
      IAMUser:
      - "cucumber"
      - type: "glob"
        value: "*tfc*"
      IAMUserPolicyAttachment:
      - "cucumber -> AdministratorAccess"
      - type: "glob"
        value: "*tfc* -> AdministratorAccess"
      IAMUserAccessKey:
      - type: "glob"
        value: "cucumber -> *"
      - type: "glob"
        value: "*tfc* -> *"
