regions:
- sa-east-1 # Sao Paulo
- us-east-1 # North Virginia
- eu-central-2 # Z├╝rich
- eu-central-1 # Frankfurt
- global

account-blocklist:
- "999999999999" # production

accounts:
  "298410952490":
    filters:
      IAMUser:
      - "banana"
      - "tfc"
      - "nuker"
      IAMUserPolicyAttachment:
      - "banana -> AdministratorAccess"
      - "tfc -> AdministratorAccess"
      - "nuker -> AdministratorAccess"
      IAMUserAccessKey:
      - type: "glob"
        value: "banana -> *"
      - type: "glob"
        value: "tfc -> *"
      - type: "glob"
        value: "nuker -> *"
      IAMVirtualMFADevice:
      - type: "glob"
        value: "arn:aws:iam::298410952490:mfa/*"
      IAMLoginProfile:
      - type: "glob"
        value: "*banana*"
      - type: "glob"
        value: "*codespace*"

